//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuiroFeet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public int stock { get; set; }
        public int id_proveedor { get; set; }
        public string categoria { get; set; }
    
        public virtual Proveedor Proveedore { get; set; }
    }
}
