//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analisis.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOrden
    {
        public int id_detalle { get; set; }
        public int id_orden { get; set; }
        public int id_producto { get; set; }
        public int qty { get; set; }
        public Nullable<decimal> precio_unidad { get; set; }
        public Nullable<decimal> subtotal { get; set; }
    
        public virtual OrdenesCompra OrdenesCompra { get; set; }
    }
}
