//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analisis.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int id { get; set; }
        public int id_producto { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> publico { get; set; }
    
        public virtual Productos Productos { get; set; }
    }
}
