//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analisis.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public Productos()
        {
            this.Inventario = new HashSet<Inventario>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int id_proveedor { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> activo { get; set; }
    
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
