//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analisis.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuiroFeetEntities1 : DbContext
    {
        public QuiroFeetEntities1()
            : base("name=QuiroFeetEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Citas> Citas { get; set; }
        public DbSet<Clientes> Clientes { get; set; }
        public DbSet<Empleados> Empleados { get; set; }
        public DbSet<Ordenes> Ordenes { get; set; }
        public DbSet<Servicios> Servicios { get; set; }
        public DbSet<Ventas> Ventas { get; set; }
        public DbSet<Proveedores> Proveedores { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<Inventario> Inventario { get; set; }
        public DbSet<Productos> Productos { get; set; }
    }
}
