//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analisis.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ventas()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public int id { get; set; }
        public int id_cliente { get; set; }
        public string servicio { get; set; }
        public string detalle { get; set; }
        public decimal monto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string NumeroRecibo { get; set; }
        public string Estado { get; set; }

        public virtual Clientes Clientes { get; set; }
        public virtual Clientes Clientes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
    }
}
